{
 "title": "Rancher Slack",
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  {
   "title": "Q2 Targets",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "content": "<ul>\n<li><b>New Users:</b> 1866</li>\n<li><b>Avg/Day:</b> 20.5</li>\n</ul>"
  },
  {
   "title": "New Users This Quarter",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT COUNT([User]) FROM dbo.UserJoinedGeneralEvents WHERE DATEPART(QUARTER, Timestamp) = DATEPART(QUARTER, GETDATE()) GROUP BY DATEPART(QUARTER, [Timestamp]) "
    }
   ]
  },
  {
   "title": "Avg. Users/Day This Quarter",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT CONVERT(real, COUNT([User])) / (select datediff(day,dateadd(quarter,datediff(quarter,0,GETDATE()),0),GETDATE())) FROM dbo.UserJoinedGeneralEvents WHERE DATEPART(QUARTER, Timestamp) = DATEPART(QUARTER, GETDATE()) GROUP BY DATEPART(QUARTER, [Timestamp]) "
    }
   ]
  },
  {
   "title": "Avg. Users/Day This Year",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "-- This query contains an adjustment for 2019, remove the subracted days in 2020\nSELECT \n    CONVERT(real, COUNT([User])) / (DATEPART(DAYOFYEAR, GETDATE()) - 70)\nFROM \n    dbo.UserJoinedGeneralEvents \nWHERE \n    DATEPART(year, Timestamp) = DATEPART(year, GETDATE()) \nGROUP BY \n    DATEPART(year, [Timestamp]) "
    }
   ]
  },
  {
   "title": "New Users Today",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT COUNT(User) FROM dbo.UserJoinedGeneralEvents WHERE DATEPART(DAYOFYEAR, [Timestamp]) = DATEPART(DAYOFYEAR, GETDATE()) "
    }
   ]
  },
  {
   "title": "Posts Today",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT c.Name, Count(m.Id) as Count\nFROM dbo.MessageHistory m \n    INNER JOIN dbo.Channels c \n    ON c.Id = m.Channel \nWHERE DATEPART(DAYOFYEAR, timestamp) = DATEPART(DAYOFYEAR, GETDATE())\nGROUP BY c.Name \nORDER BY COUNT(m.Id) DESC, c.Name ASC"
    }
   ]
  },
  {
   "title": "Posts this Week",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT c.Name, Count(m.Id) as Count\nFROM dbo.MessageHistory m \n    INNER JOIN dbo.Channels c \n    ON c.Id = m.Channel \nWHERE DATEPART(WEEK, timestamp) = DATEPART(WEEK, GETDATE())\nGROUP BY c.Name \nORDER BY COUNT(m.Id) DESC, c.Name ASC"
    }
   ]
  },
  {
   "title": "Posts this Month",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT c.Name, Count(m.Id) as Count\nFROM dbo.MessageHistory m \n    INNER JOIN dbo.Channels c \n    ON c.Id = m.Channel \nWHERE DATEPART(month, timestamp) = DATEPART(month, GETDATE())\nGROUP BY c.Name \nORDER BY COUNT(m.Id) DESC, c.Name ASC"
    }
   ]
  },
  {
   "title": "Posts this Quarter",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT c.Name, Count(m.Id) as Count\nFROM dbo.MessageHistory m \n    INNER JOIN dbo.Channels c \n    ON c.Id = m.Channel \nWHERE DATEPART(QUARTER, timestamp) = DATEPART(QUARTER, GETDATE())\nGROUP BY c.Name \nORDER BY COUNT(m.Id) DESC, c.Name ASC"
    }
   ]
  },
  {
   "title": "Posts this Year",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT c.Name, Count(m.Id) as Count\nFROM dbo.MessageHistory m \n    INNER JOIN dbo.Channels c \n    ON c.Id = m.Channel \nWHERE DATEPART(YEAR, timestamp) = DATEPART(YEAR, GETDATE())\nGROUP BY c.Name \nORDER BY COUNT(m.Id) DESC, c.Name ASC"
    }
   ]
  },
  {
   "title": "Posts Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(m.Id) as Posts,\n  c.Name as Channel,\n  CONVERT(date, m.Timestamp) as time       \nFROM\n  dbo.MessageHistory m INNER JOIN Channels c on m.Channel = c.Id\nWHERE\n  $__timeFilter(m.Timestamp)\nGROUP BY c.Name, CONVERT(date, m.Timestamp)\nORDER BY CONVERT(date, m.Timestamp) ASC"
    }
   ]
  },
  {
   "title": "New Users: Daily",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n        CONVERT(date, m.timestamp) AS time,\n        COUNt(m.[User]) as NewUsers\nFROM dbo.UserJoinedGeneralEvents m\nGROUP BY CONVERT(date, m.timestamp)\nORDER BY CONVERT(date, m.timestamp)"
    }
   ]
  },
  {
   "title": "Total User Posts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n        u.Name,\n        CONVERT(date, m.timestamp) AS time,\n        SUM(COUNT(m.Id)) OVER ( PARTITION BY u.Name ORDER BY Convert(date, m.Timestamp) ROWS BETWEEN unbounded preceding  and current row ) as PostSum\nFROM dbo.MessageHistory m INNER JOIN dbo.Users u ON m.[User] = u.Id\nGROUP BY u.Name, CONVERT(date, m.timestamp)\nORDER BY CONVERT(date, m.timestamp), u.Name"
    }
   ]
  }
 ]
}