name: Build and Push Dockerfiles

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run the CI Script
      run: ./scripts/ci.sh
    - name: Test Run
      run: ls -al
